### PR TITLE
Allow setting a "defaultSeverity" in the config

### PR DESCRIPTION
**Pull request by Gama11**
The "default defaultSeverity" is currently "INFO", but being able to change that makes things a lot more flexible.

### CODE REVIEW

**Comment by adireddy** [comment]
v1.2.4 has this update.

**Comment by Gama11** [comment]
It looks like you forgot the `v` in front of the tag for 1.2.4. ;)

**Comment by adireddy** [comment]
yes I did :)

**Comment by Gama11** [comment]
I think Git lets you change tag names.

**Comment by adireddy** [comment]
It will create another tag with the new name. I will leave it like that. Not a biggie :)

**Pull request merged**
