### PR TITLE
merge token tree into main dev branch

### PR DESCRIPTION
**Pull request by AlexHaxe**
- implemented a token tree builder, adding a new class of checks based on tokens and their relationship
  - token tree builder arranges all tokens into a tree structure
  - all tree nodes have the same type with position info
  - easy traversal of token tree
  - access to parent token
- added EmptyBlock, OperatorWrap, SeparatorWrap, WhitespaceAfter and WhitespaceAround checks
- refactored LeftCurly, RightCurly and NeedBraces checks to use token tree
- moved block and whitespace checks into separate packages
- removed BlockFormat check -> use LeftCurly, RightCurly and EmptyBlock instead

possible issues:
- unhandled combinations of tokens can result in endless loops or stacktraces in checks using token-tree
  - temporary solution -> disable check in config
  - open an issue with sample code

### CODE REVIEW

**Comment by AlexHaxe** [comment]
There are some new Spacing check messages when running build.hxml, I am not sure why they don't show up in previous Travis build logs. 
I will fix them and push another commit.

**Comment by Gama11** [comment]
I extended `SpacingCheck` earlier today: #94

**Comment by AlexHaxe** [comment]
I have seen that and merged your changes into token-tree, but the travis build for your merge does not show those messages (https://travis-ci.org/adireddy/haxe-checkstyle/builds/113350005)

**Comment by adireddy** [comment]
all good in a couple of projects I checked :+1: 

I will prepare the release in the next couple of days.

**Pull request merged**
