### PR TITLE
Spacing checks: require no spaces

### LINKED ISSUE #302: Spacing check does not ensure absence of space.
With such settings
```
"type": "Spacing",
"props": {
    "spaceIfCondition": false,
```
Checkstyle does not notify me if there is a space between `if` and `(`.
I want it to print a message in report if there is a code like this in sources:
```
if (cond) { //space between if and ( should be reported
```
The same for other spacing settings (while, for, switch etc)

### PR DESCRIPTION
**Pull request by RealyUniqueName**
This PR fixes #302.

Since now some of spacing settings need three options i had to change them to a string. Those strings will be treated as [`checkstyle.checks.Directive`](https://github.com/RealyUniqueName/haxe-checkstyle/blob/require-no-spaces/src/checkstyle/checks/Directive.hx).

Old configs (with booleans) still supported (see [Directive.fromAny()](https://github.com/RealyUniqueName/haxe-checkstyle/blob/require-no-spaces/src/checkstyle/checks/Directive.hx#L13))

### CODE REVIEW

**Comment by adireddy** [comment]
use `Dynamic` instead of `Any` as the build is failing for Haxe 3.2.1

src/checkstyle/checks/Check.hx:34: lines 34-36 : Type not found : Any

**Comment by RealyUniqueName** [comment]
Usage of Dynamic is reported by checkstyle when checking checkstyle )

```
src/checkstyle/checks/whitespace/SpacingCheck.hx:36: characters 17-308 : Info: "value" type is "Dynamic"
```

**Comment by adireddy** [comment]
:) that's still fine, some things we can't avoid.

You can add the class to the `exclude` section in `checkstyle.json`. This is to exclude known issues.

**Comment by RealyUniqueName** [comment]
Done! Waiting for CI.

**Comment by adireddy** [comment]
@RealyUniqueName Is this change backwards compatible with `true`/`false` values?

**Comment by RealyUniqueName** [comment]
Yes: https://github.com/HaxeCheckstyle/haxe-checkstyle/blob/dev/src/checkstyle/checks/Directive.hx#L22

**Comment by adireddy** [comment]
just noticed it :)

**Comment by adireddy** [comment]
v2.1.7 is out

**Comment by RealyUniqueName** [comment]
Thanks!

**Pull request merged**
