### PR TITLE
added NestedIfDepth, NestedForDepth and NestedTryDepth checks

### PR DESCRIPTION
**Pull request by AlexHaxe**
Hi,

just added a few more checks:
- NestedForDepth checks for nested for/while loops (default: 1 => max 2 levels)
- NestedIfDepth checks for nested if-else blocks (default: 1 => max 2 levels)
- NestedTryDepth checks for nested try-catch blocks (default: 1 => max 2 levels)

Severity for all Nested*Depth checks is set to ERROR.

Adjusted default(max=7) for ParameterNumber check to match default of official checkstyle documentation

### CODE REVIEW

**Comment by adireddy** [comment]
:+1: 

Hey @AlexHaxe, if you want to contribute regularly I can add you as collaborator to this project. Let me know.

**Comment by AlexHaxe** [comment]
I'm not sure if I can find the time to work regularly on this project but then again there is no fixed release schedule, so I might be able to contribute a few features from time to time.

**Comment by adireddy** [comment]
That's absolutely fine. Adding you as a collaborator now so you can commit to dev branch directly and when you think the features are ready for the release raise a pull request to master and I will take care of the haxelib release.

**Comment by AlexHaxe** [comment]
Sounds good!

**Pull request merged**
