### PR TITLE
new ExtendedEmptyLines check, fixes #150, fixes #151, fixes #233, fixes #240

### LINKED ISSUE #150: EmptyLinesCheck: requireEmptyLineAfter* should ignore empty declarations
Using `@:bitmap`, `@:file` etc meta, there's a use case for empty classes. If combined with e.g. conditionals, the line after the declaration isn't empty.

``` haxe
#if true
@:bitmap("assets/images/logo/logo.png")
class GraphicLogo extends BitmapData {}
#end
```

``` json
{
    "checks": [
        {
            "type": "EmptyLines"
        }
    ]
}
```

```
./source/Test.hx:4: character 0 : Info: Empty line required after class declaration
```

---

There's also use cases for empty interfaces (interfaces with `@:autoBuild` meta propagate that to implementing classes) and empty abstracts, for example for types like this:

``` haxe
abstract OneOfTwo<T1, T2>(Dynamic) from T1 from T2 to T1 to T2 {}
```

### LINKED ISSUE #151: EmptyLinesCheck: requireEmptyLineAfter* should have inverse
For LeftCurly style EOL, requiring an empty line after the declaration makes sense. When the left curly is placed in a new line however, you probably want to enforce the inverse and _not_ allow any empty lines there.

Valid:

``` haxe
class Test
{
    public var field:Int;
}
```

Invalid:

``` haxe
class Test
{

    public var field:Int;
}
```

### LINKED ISSUE #233: EmptyLinesCheck needs an option for empty lines at type end
`EmptyLinesCheck` should have an option to disallow empty lines before the closing brace of a type, e.g.:

``` haxe
class Test
{
    public function foo();

}
```

### LINKED ISSUE #240: Check to detect missing new line at end of file
It's _generally_ a good practice to enforce a newline character at end of files.

Maybe it could deserve a check for this?

### PR DESCRIPTION
**Pull request by AlexHaxe**
fixes #150 
fixes #151 
fixes #233 
fixes #240

### CODE REVIEW

**Comment by AlexHaxe** [comment]
@Gama11 I'm keeping this PR open for now, it needs some unittests and probably has a few kinks and quirks to fix and I may refactor some things around before merging. 
There are a lot of options to the new ExtendedEmptyLines check, maybe too many, maybe it's overkill, maybe I'm missing some, I would love to hear your opinion on it (or anyone else's, it's not strictly limited to @Gama11 :)).

**Comment by Gama11** [comment]
Wow. :)

>maybe too many, maybe it's overkill, maybe I'm missing some,

I'm mostly wondering if there's a really use case for controlling this for each individual kind of type that Haxe has, i.e. class/interface/abstract/enum/typedef. If not, a lot of this could be summarized as "beginType" / "endType", and configuration would be much less tedious.

**Comment by AlexHaxe** [comment]
Many people most likely will use the same begin-/endType policies for all types, so only giving them those two options would be enough. Programming wise it doesn't make much of a difference to have them separate. It's configuring 2 versus 10 different yet quite similiar policies which makes it a bit tedious.

But for e.g. checkstyle we have an empty line for beginClass and beginInterface (at least in a majority of cases) and no empty line for beginTypedef. I could cover that by using `upto`, but I would not be able to enforce it for classes to have an empty line and for typedefs to have none. 

So I'm a bit undecided here, yes there are a lot of options, but they also provide a lot of flexibility.

I also thought about splitting the check into multiple different checks, but having six or seven EmptyLine checks doesn't appear to improve the number of configuration options. 
Also if people want to have e.g. different `max` values for different places they will have to add multiple instances of `ExtendedEmptyLines` with lots of `ignore`s, having more specialized empty lines checks might make it easier, or maybe not.

**Comment by Gama11** [comment]
Perhaps allow bundling the flags together, but also optionally specifying them individually? Something like:

```js
"beginType": {
    "default": "exact"
     // all the other properties are @:optional
}
```

```js
"beginType": {
    "default": "exact",
    "enum": "none",
    "typedef": "none"
     // default overriden for enum and typedef, but used for all other types
}
```

**Comment by AlexHaxe** [comment]
hmm... maybe it should be flipped around, e.g. like:
```
"max": 1,
"defaultPolicy": "none",
"ignore": [],
"none": [
    "endAbstract",
    "endClass",
    "beginEnum",
    "endEnum",
    :
],
"exact": [
    "beginClass",
    "beginAbstract",
    :
],
"upto": [],
"atleast": []
```

though, it might require changes to the detection logic...

**Comment by Gama11** [comment]
That might work, but it doesn't really seem related to my suggsetion? You still have to specifiy each type individually there, right?

I also wonder if there's a use case for a `max` that's different for different "locations"..

**Comment by AlexHaxe** [comment]
`defaultPolicy` applies to all places, that were not specified, so you only have to list policies and places that don't use the global default policy. It's not as versatile as your proposal, but it makes overall configuration easier and shorter, especially if you have multiple instances of `ExtendedEmptyLines` check. You can set default to `ignore` and only specify places you want special treatment for.

Well someone might want to impose two empty lines between class methods, while everywhere else they want one - I've seen a company's code that used three empty lines between methods.

**Comment by Gama11** [comment]
>defaultPolicy

Oh, right, I missed that part. That should definitely reduce the amount of configuration needed by a lot as well.

**Comment by AlexHaxe** [comment]
yeah, I took your concept of `default` and went from there. I think it's a huge improvement.

Now I have to find time to implement it....

**Pull request merged**
