### PR TITLE
Test coverage

### PR DESCRIPTION
**Pull request by adireddy**

### CODE REVIEW

**Comment by AlexHaxe** [comment]
yay, coverage reports!

Line coverage doesn't seem to work, I guess we need a custom client to get correct numbers.

**Comment by adireddy** [comment]
yes.. it still have issues... the numbers look correct in the report but codecov is not picking up correctly. Will keep trying to make it perfect.

**Comment by AlexHaxe** [comment]
When you look at the raw report https://codecov.io/api/github/adireddy/haxe-checkstyle it doesn't look right. A different printer client might help (they claim to support a few formats), or we might have to patch one of mcover's clients to spit out what codecov needs – or we might take a look around to see if some other Haxe project is already using codecov and _steal_ from them ;)

**Comment by adireddy** [comment]
I think it looks better now. I don't think any Haxe project is using codecov or, in fact, any other coverage integration. If you come accross anything let me know.

The only file format mcover supports is EMMAPrintClient and that didn't work with codecov.

**Comment by AlexHaxe** [comment]
I guess that's a correct assumption, I haven't come accross any other project using it.

I currently use EMMAPrintClient for my Jenkins projects, but in that combination Jenkins' Emma plugin doesn't go to source code level, you can only view packages, classes and functions (haven't tried it with a real Java project, maybe that's all Emma plugin can do). 
I tried hacking together a Jacoco client for mcover, only to find out Jenkins' Jacoco plugin wants to run Jacoco by itself and doesn't accept xml files.

**Pull request merged**
