### PR TITLE
Rename AccessOrderCheck to ModifierOrderCheck

### PR DESCRIPTION
**Pull request by Gama11**
This makes it consistent with the Java version.

### CODE REVIEW

**Comment by Gama11** [comment]
@adireddy This is a breaking change I guess.

**Comment by Gama11** [comment]
Next step would be to rename `PublicPrivateCheck` to `RedundantModifierCheck` and move them to `modifier`.

**Comment by adireddy** [comment]
Just added functionality in `dev` to allow multiple names to checks so that old checks will not break as shown below.

`@name("ModifierOrder", "AccessOrder")`

**Comment by Gama11** [comment]
Oh, neat. Should one of them be marked as deprecated somehow?

**Comment by adireddy** [comment]
Added `[DEPRECATED]` suffix to the description. https://github.com/adireddy/haxe-checkstyle/commit/8973d66d1b7723da5cd72ef862577374a5b3b529

Only visible when `--list-checks` is used. Need to find a way to show that when checkstyle runs.

**Comment by Gama11** [comment]
That could be interpreted as the check having been removed, when it's really only been renamed.

**Comment by adireddy** [comment]
Deprecation is about discouraging the use. I don't think it means removed. That's how I interpret.

**Comment by Gama11** [comment]
I think it should mention the new name at least.

**Comment by adireddy** [comment]
done.

`PublicPrivate:
  Checks for redundant modifiers [DEPRECATED, use RedundantModifer instead]
`

**Pull request merged**
