### PR TITLE
lot of refactoring, removed naming check, etc, etc

### PR DESCRIPTION
**Pull request by adireddy**
@AlexHaxe spent the last few hours straight after #wwx2015 refactoring :)
- Removed NamingCheck and using other checks like MemberName, MethodName, etc to achieve same results
- The current issue count of checksytle check on itself is 4 (from 400+) with a little bit of cheating :) like I have increased default line length from 80 to 200 and using SuppressWarnings in a few places.
- It still needs a bit more refactoring so please continue fixing issues or make thing better.

### CODE REVIEW

**Comment by AlexHaxe** [comment]
wow nice work :+1:

As to the cheating: there are some checks that use a string search to find offending pieces of code, I think we need to refactor that someday.
I think the line length default should be higher than 80, but probably lower than 200. It all depends on your IDE and the number of toolbars and sidebars you are using, also screen size. But I think 120, 140 or even 160 should fit on a screen of a modern development system.

**Comment by alebianco** [comment]
The problem is when you have a "public static inline function" with a
couple complex parameters... Eats up space like crazy. But yes I generally
set the config to 120 and then typedef most callbacks and generic types.

Also, the enum pattern matching increases a lot the score of the cyclomatic
complexity, we could try use a strategy approach but it would be less
explicit

**Comment by adireddy** [comment]
@AlexHaxe yes I agree. Checks like AnonymousCheck uses string search which should be refactored.

Let's revisit LineLengthCheck again.

BTW, are you in the conference @AlexHaxe. Just checking :)

**Comment by AlexHaxe** [comment]
No, couldn't go, I watched the stream instead

**Pull request merged**
