### PR TITLE
Always consider abstract fields in checks, not just class fields

### PR DESCRIPTION
**Pull request by Gama11**

### CODE REVIEW

**Comment by Gama11** [comment]
Hm, I guess this can be refactored using `ExprUtils.walkFile()`...

**Comment by Gama11** [comment]
Hm, it seems there are a lot more checks with the same issue, so don't merge yet..

**Comment by Gama11** [comment]
@adireddy What's `resources/config.json` for? It doesn't appear to be used for the self-check in `build.hxml`.

**Comment by Gama11** [comment]
Well, this PR certainly got a little bigger than originally intended...

I refactored the tests to use a new `forEachField()` method added to `Check.hx`. This makes sure that both the abstract and class fields are covered and also removes quite a bit of redundant code.

I also added a mechanism to easily test both the abstract and the class case. This required rewriting a few `assertEquals()` to `assertMsg()` calls (which is probably nicer anyway).

**Comment by adireddy** [comment]
Great :+1:

`resources/config.json` is no longer used.

**Comment by Gama11** [comment]
So that can be removed?

I also just noticed that there is no test for `CyclomaticComplexityCheck`, so I hope that's still working correctly.

**Comment by adireddy** [comment]
I removed `resources/config.json`. I am going to do a quick test in my project.

**Comment by adireddy** [comment]
all good :+1: 

Also added a basic test for `CyclomaticComplexityCheck`.

**Comment by AlexHaxe** [comment]
Shouldn't we keep config.json as an example for new users? Maybe rename it to sample-config.json.

**Comment by adireddy** [comment]
good point, so we need to keep it up to date with all the changes.

**Pull request merged**
