### PR TITLE
Fix/multiline file boundary issue

### PR DESCRIPTION
**Pull request by francoisvn**
I discovered a bug where the multiline status of one file can impact a later file. I noticed this with the `IndentationCharacterCheck`, but I think it would be present in other checks that extend `LineCheckBase`. No idea if this is the correct way to fix this, but it resolved the issue for me. Unfortunately I can't share the exact code, but I can try create a small test case for reproduction if that would help.

Similar issues, where checks can cross file boundaries, are probably still there with other checks (maybe even still these). It doesn't seem like there is generally anything to prevent against this. A more general solution is to re-create each check with each file (might be slow), or have something like an `init()` function that gets called before each file, and move most/all of the code in the constructors there.

### CODE REVIEW

**Comment by adireddy** [comment]
Thanks @francoisvn. Can you add the tests [here](https://github.com/HaxeCheckstyle/haxe-checkstyle/blob/dev/test/checks/whitespace/IndentationCharacterCheckTest.hx) pls just to make sure it doesn't break anything.

**Comment by francoisvn** [comment]
I added 2 tests. The first would have previously failed, but my workaround fixes it (`testFileBoundaryIndentation()`) and the second still fails (`testMultilineQuoteIndentation()`).

So there are 2 underlying issues, which I haven't properly addressed in this PR (cause I don't know the codebase well enough):
- Checks can cross file boundaries.
- Multiline detection in `LineCheckBase` is inherently buggy.

**Comment by Gama11** [comment]
One of the added tests is failing:

https://travis-ci.org/HaxeCheckstyle/haxe-checkstyle/builds/153291219#L550

**Comment by francoisvn** [comment]
Should I maybe remove the test that fails and create an issue for that? It's not a trivial fix, which is why I haven't done it myself.

In addition, it feels like the file boundary issue requires a bit of refactoring to properly fix.

**Comment by Gama11** [comment]
Yes, can't merge a PR that introduces failing tests.

**Comment by francoisvn** [comment]
Ok, I've reverted that test and created an issue here: https://github.com/HaxeCheckstyle/haxe-checkstyle/issues/278

I still think the file boundary issue I've mentioned needs further investigation, but reporting an issue for that doesn't seem sensible, so I don't know how to take it further. I don't know the codebase well enough to know how best to fix it, and it's a non-trivial change, but I think it's important that it gets investigated. Recommendations for what I can do are welcome.

**Comment by Gama11** [comment]
Thanks!

**Comment by francoisvn** [comment]
Great. What should I do about the file boundary issue, or is that not important? Should I create an issue? It seems rather important to me, as someone that would like to rely on this tool...

**Comment by Gama11** [comment]
Creating an issue definitely can't hurt.

**Pull request merged**
